#!/bin/bash

#SUPPORTED_ARCHITECTURES=(armeabi-v7a)
SUPPORTED_ARCHITECTURES=(x86)
ANDROID_NDK_ROOT_PATH=~/android-ndk-r10e
ANDROID_API_VERSION=19
NDK_TOOLCHAIN_ABI_VERSION=4.8

NUMBER_OF_CORES=$(nproc)
HOST_UNAME=$(uname -m)
